#
#   Configuration and settings for Knockout
#
banner: |
  // Knockout JavaScript library v<%= pkg.version %>
  // (c) Steven Sanderson - <%= pkg.homepage %>
  // License: <%= pkg.licenses[0].type %> (<%= pkg.licenses[0].url %>)

# Build scripts reside here
scriptsDir: build/fragments/

# knockout-latest[.debug].js goes here when compiled
buildDir: build/output/
build:
  main: knockout-latest.js
  debug: knockout-latest.debug.js

# Created in tagged 'release' versions
distDir: dist/
dist:
  min: knockout.min.js
  debug: knockout.debug.js

# These are injected into runner.template.html to produce runner.*.html
JQUERY_JS: node_modules/jquery/dist/jquery.js
# In due course, when upgrading to Jasmine 2.0, the spec/helper/
# files could be replaced with node_modules/jasmine-core/lib/jasmine-core
JASMINE_JS: spec/helpers/lib/jasmine.js
JASMINE_HTML_JS: spec/helpers/lib/jasmine-html.js
JASMINE_CSS: spec/helpers/lib/jasmine.css
# When Modernizr finally makes it into npm it could perhaps be installed
# that way. It is also notably in grunt-modernizr.
MODERNIZR_JS: spec/helpers/lib/modernizr.js

# Added to runner[.modernizr|.jquery].html
AUTOGEN_WARNING:  AUTOGENERATED FROM spec/helpers/runner.template.html

# Files that have their 'version' bumped
PACKAGE_FILES:
  - ./package.json
  - ./bower.json

# Closure compiler
closure_options:
  compilation_level: ADVANCED_OPTIMIZATIONS

# Files that have their trailing spaces checked on lint
trailingSpaceSources:
  - 'spec/*.{js,html,css,bat,ps1,sh}'
  - 'src/*.{js,html,css,bat,ps1,sh}'
  - 'build/fragments/*'

# Listening for changes
livereload_port: 35728

# Source files
sources:
  - src/namespace.js
  - src/google-closure-compiler-utils.js
  - src/version.js
  - src/utils.js
  - src/utils.domData.js
  - src/utils.domNodeDisposal.js
  - src/utils.domManipulation.js
  - src/memoization.js
  - src/subscribables/extenders.js
  - src/subscribables/subscribable.js
  - src/subscribables/dependencyDetection.js
  - src/subscribables/observable.js
  - src/subscribables/observableArray.js
  - src/subscribables/observableArray.changeTracking.js
  - src/subscribables/dependentObservable.js
  - src/subscribables/mappingHelpers.js
  - src/binding/selectExtensions.js
  - src/binding/expressionRewriting.js
  - src/virtualElements.js
  - src/binding/bindingProvider.js
  - src/binding/bindingAttributeSyntax.js
  - src/binding/defaultBindings/attr.js
  - src/binding/defaultBindings/checked.js
  - src/binding/defaultBindings/css.js
  - src/binding/defaultBindings/enableDisable.js
  - src/binding/defaultBindings/event.js
  - src/binding/defaultBindings/foreach.js
  - src/binding/defaultBindings/hasfocus.js
  - src/binding/defaultBindings/html.js
  - src/binding/defaultBindings/ifIfnotWith.js
  - src/binding/defaultBindings/options.js
  - src/binding/defaultBindings/selectedOptions.js
  - src/binding/defaultBindings/style.js
  - src/binding/defaultBindings/submit.js
  - src/binding/defaultBindings/text.js
  - src/binding/defaultBindings/uniqueName.js
  - src/binding/defaultBindings/value.js
  - src/binding/defaultBindings/visible.js
  - src/binding/defaultBindings/click.js
  - src/templating/templateEngine.js
  - src/templating/templateRewriting.js
  - src/templating/templateSources.js
  - src/templating/templating.js
  - src/binding/editDetection/compareArrays.js
  - src/binding/editDetection/arrayToDomNodeChildren.js
  - src/templating/native/nativeTemplateEngine.js
  - src/templating/jquery.tmpl/jqueryTmplTemplateEngine.js

# Test files
node_spec: spec/spec.node.js

spec_files:
  - ./spec/arrayEditDetectionBehaviors.js
  - ./spec/arrayToDomEditDetectionBehaviors.js
  - ./spec/asyncBehaviors.js
  - ./spec/memoizationBehaviors.js
  - ./spec/subscribableBehaviors.js
  - ./spec/observableBehaviors.js
  - ./spec/observableArrayBehaviors.js
  - ./spec/observableArrayChangeTrackingBehaviors.js
  - ./spec/dependentObservableBehaviors.js
  - ./spec/dependentObservableDomBehaviors.js
  - ./spec/extenderBehaviors.js
  - ./spec/domNodeDisposalBehaviors.js
  - ./spec/mappingHelperBehaviors.js
  - ./spec/expressionRewritingBehaviors.js
  - ./spec/bindingPreprocessingBehaviors.js
  - ./spec/nodePreprocessingBehaviors.js
  - ./spec/bindingAttributeBehaviors.js
  - ./spec/bindingDependencyBehaviors.js
  - ./spec/templatingBehaviors.js
  - ./spec/jsonPostingBehaviors.js
  - ./spec/nativeTemplateEngineBehaviors.js
  - ./spec/utilsBehaviors.js
  - ./spec/defaultBindings/attrBehaviors.js
  - ./spec/defaultBindings/checkedBehaviors.js
  - ./spec/defaultBindings/clickBehaviors.js
  - ./spec/defaultBindings/cssBehaviors.js
  - ./spec/defaultBindings/enableDisableBehaviors.js
  - ./spec/defaultBindings/eventBehaviors.js
  - ./spec/defaultBindings/foreachBehaviors.js
  - ./spec/defaultBindings/hasfocusBehaviors.js
  - ./spec/defaultBindings/htmlBehaviors.js
  - ./spec/defaultBindings/ifBehaviors.js
  - ./spec/defaultBindings/ifnotBehaviors.js
  - ./spec/defaultBindings/optionsBehaviors.js
  - ./spec/defaultBindings/selectedOptionsBehaviors.js
  - ./spec/defaultBindings/styleBehaviors.js
  - ./spec/defaultBindings/submitBehaviors.js
  - ./spec/defaultBindings/textBehaviors.js
  - ./spec/defaultBindings/uniqueNameBehaviors.js
  - ./spec/defaultBindings/valueBehaviors.js
  - ./spec/defaultBindings/visibleBehaviors.js
  - ./spec/defaultBindings/withBehaviors.js
